# Generated by Django 3.0.5 on 2020-10-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=150)),
                ('emp_con', models.CharField(max_length=15)),
                ('emp_salary', models.FloatField()),
            ],
        ),
    ]
